"""adicionar coluna ordem itens

Revision ID: 3245d65ddab1
Revises: 50d49297ae6a
Create Date: 2025-11-24 22:15:52.835074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3245d65ddab1'
down_revision: Union[str, Sequence[str], None] = '50d49297ae6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens', sa.Column('ordem', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itens', 'ordem')
    # ### end Alembic commands ###
