"""criar tabela itens

Revision ID: 50d49297ae6a
Revises: f6cb6c8441ee
Create Date: 2025-11-24 20:40:17.490289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d49297ae6a'
down_revision: Union[str, Sequence[str], None] = 'f6cb6c8441ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Integer(), server_default='1', nullable=False),
    sa.Column('comprado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lista_id'], ['listas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_id'), 'itens', ['id'], unique=False)
    op.create_index(op.f('ix_itens_lista_id'), 'itens', ['lista_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_lista_id'), table_name='itens')
    op.drop_index(op.f('ix_itens_id'), table_name='itens')
    op.drop_table('itens')
    # ### end Alembic commands ###
